apiVersion: v1
kind: Secret
metadata:
  name: {{ include "log-processing-api.fullname" . }}
type: Opaque
stringData:
  MONGO_URI: {{ .Values.env.MONGO_URI | quote }}
  REDIS_URL: {{ .Values.env.REDIS_URL | quote }}

