FROM python:3.9-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./app .

# Command to start the Celery worker
CMD ["celery", "-A", "app.celery_app", "worker", "--loglevel=info"]
