version: '3.8'

services:
  # FastAPI Application
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - MONGO_DETAILS=mongodb://mongo:27017

  # Celery Worker
  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: celery_worker
    depends_on:
      - redis
    environment:
      - MONGO_DETAILS=mongodb://mongo:27017
      - CELERY_BROKER_URL=redis://redis:6379/0

  # Redis for message queuing
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"

  # MongoDB for storing logs
  mongo:
    image: "mongo:latest"
    container_name: mongo
    ports:
      - "27017:27017"
